version: '3.5'

networks:
    taskmanagerapp:
  

services:
  taskmanagerdb:
    container_name: taskmanager-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=password@12345#
    - MSSQL_PID=Express
    networks:
     - taskmanagerapp
  taskmanager.api3:
    container_name: taskmanager-api
    image: ${DOCKER_REGISTRY-}taskmanagerapi3
    build:
      context: .
      dockerfile: TaskManager.API3\Dockerfile
    ports:
        - 8001:80
    depends_on:
        - taskmanagerdb
    environment:
        - DB_HOST=taskmanagerdb
        - DB_NAME=TaskDb
        - DB_SA_PASSWORD=password@12345#
        - FrontendPort=http://localhost:3000
    networks:
        - taskmanagerapp
  taskmanager.frontend:
    container_name: taskmanager-frontend001
    build:
        context: ./taskmanager.frontend
        dockerfile: Dockerfile
        args:
            buildno: 002
    volumes:
      - /app/node_modules
    ports:
        - 3000:3000
   
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
    - taskmanager.api3
    networks:
    - taskmanagerapp


       
            