version: '3.4'

networks:
    taskmanagerapp:
  

services:
  taskmanagerdb:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
     - 8002:1433
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=password@12345#
    - MSSQL_PID=Express
    networks:
     - taskmanagerapp
  taskmanager.api3:
    container_name: taskmanager-app
    image: ${DOCKER_REGISTRY-}taskmanagerapi3
    build:
      context: .
      dockerfile: TaskManager.API3\Dockerfile
    ports:
        - 8001:80
    depends_on:
        - taskmanagerdb
    environment:
        - DB_HOST=taskmanagerdb
        - DB_NAME=TaskDb
        - DB_SA_PASSWORD=password@12345#
    networks:
        - taskmanagerapp
